[package]
name = "vesper"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[[bin]]
name = "vesper"
path = "src/main.rs"

[dependencies]
vesper-core = { path = "../core" }
tokio = { version = "1", features = ["macros", "rt"] }
clap = { version = "4", features = ["derive"] }
directories = "5"
anyhow = "1"
