//! Background-service management: registering the periodic `sync` job with the
//! OS scheduler.
//!
//! Windows (Task Scheduler, via `schtasks`) is implemented. Other platforms are
//! stubbed behind the same trait so a systemd user unit / launchd agent can be
//! added later without touching the CLI. Task Scheduler is chosen over a real
//! Windows Service because the sync is a scheduled invocation, not a resident
//! daemon (see DESIGN.md), and a per-user task needs no elevation.

#![allow(dead_code)] // Some fields/impls are platform-gated.

use std::path::Path;

use anyhow::Result;

/// Name of the scheduled task / service.
pub const TASK_NAME: &str = "WebnovelCrawlerSync";

pub struct ServiceStatus {
    pub installed: bool,
    pub detail: String,
}

/// Platform-agnostic install/uninstall/status for the background sync job.
pub trait ServiceManager {
    fn install(&self, exe: &Path, interval_minutes: u32) -> Result<()>;
    fn uninstall(&self) -> Result<()>;
    fn status(&self) -> Result<ServiceStatus>;
}

/// The service manager for the current platform.
pub fn manager() -> Result<Box<dyn ServiceManager>> {
    #[cfg(windows)]
    {
        Ok(Box::new(windows::WindowsTaskScheduler))
    }
    #[cfg(target_os = "linux")]
    {
        Ok(Box::new(linux::SystemdUser))
    }
    #[cfg(target_os = "macos")]
    {
        Ok(Box::new(macos::Launchd))
    }
    #[cfg(not(any(windows, target_os = "linux", target_os = "macos")))]
    {
        anyhow::bail!("background-service install is not implemented on this platform")
    }
}

#[cfg(windows)]
mod windows {
    use std::path::{Path, PathBuf};
    use std::process::Command;

    use anyhow::{anyhow, bail, Result};

    use super::{ServiceManager, ServiceStatus, TASK_NAME};

    /// Path to the generated hidden-launcher script (next to the DB).
    fn launcher_path() -> Result<PathBuf> {
        let db = crawler_core::default_db_path()?;
        let dir = db
            .parent()
            .ok_or_else(|| anyhow!("cannot resolve data directory"))?;
        Ok(dir.join("sync-hidden.vbs"))
    }

    /// Write a VBScript that runs `<exe> sync` with a hidden window. Launched via
    /// `wscript.exe` (which has no console of its own), this makes the scheduled
    /// run windowless — no console flash every interval.
    fn write_launcher(path: &Path, exe: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // Run's first arg is the command line: the quoted exe path + " sync".
        // In VBScript a doubled "" is one literal quote, so `"""..."" sync"`
        // yields the string `"<exe>" sync`. Window style 0 = hidden, async.
        let cmd = format!("\"\"\"{}\"\" sync\"", exe.display());
        let vbs = format!(
            "' Auto-generated by crawler. Runs the sync with no console window.\r\n\
             CreateObject(\"Wscript.Shell\").Run {cmd}, 0, False\r\n"
        );
        std::fs::write(path, vbs)
            .map_err(|e| anyhow!("writing launcher {}: {e}", path.display()))?;
        Ok(())
    }

    pub struct WindowsTaskScheduler;

    impl ServiceManager for WindowsTaskScheduler {
        fn install(&self, exe: &Path, interval_minutes: u32) -> Result<()> {
            // Register `wscript.exe "<launcher.vbs>"` rather than the console exe
            // directly, so the periodic run shows no window.
            let launcher = launcher_path()?;
            write_launcher(&launcher, exe)?;
            let tr = format!("wscript.exe \"{}\"", launcher.display());
            let out = Command::new("schtasks")
                .args([
                    "/Create",
                    "/TN",
                    TASK_NAME,
                    "/TR",
                    &tr,
                    "/SC",
                    "MINUTE",
                    "/MO",
                    &interval_minutes.to_string(),
                    "/F",
                ])
                .output()?;
            if !out.status.success() {
                bail!(
                    "schtasks /Create failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                );
            }
            Ok(())
        }

        fn uninstall(&self) -> Result<()> {
            let out = Command::new("schtasks")
                .args(["/Delete", "/TN", TASK_NAME, "/F"])
                .output()?;
            if !out.status.success() {
                bail!(
                    "schtasks /Delete failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                );
            }
            // Best-effort cleanup of the generated launcher.
            if let Ok(launcher) = launcher_path() {
                let _ = std::fs::remove_file(launcher);
            }
            Ok(())
        }

        fn status(&self) -> Result<ServiceStatus> {
            let out = Command::new("schtasks")
                .args(["/Query", "/TN", TASK_NAME])
                .output()?;
            Ok(ServiceStatus {
                installed: out.status.success(),
                detail: if out.status.success() {
                    String::from_utf8_lossy(&out.stdout).trim().to_string()
                } else {
                    "not installed".to_string()
                },
            })
        }
    }
}

// NOTE: the Linux and macOS implementations below are UNVERIFIED — they cannot
// be compiled or run on the Windows development machine (cfg-gated code is not
// type-checked here, and the C dependencies don't cross-compile). Treat them as
// a careful starting point that needs testing on a real Linux/macOS box before
// being relied on.

#[cfg(target_os = "linux")]
mod linux {
    use std::path::{Path, PathBuf};
    use std::process::Command;

    use anyhow::{anyhow, bail, Result};

    use super::{ServiceManager, ServiceStatus, TASK_NAME};

    /// systemd *user* units live here (no root needed).
    fn unit_dir() -> Result<PathBuf> {
        let base = std::env::var_os("XDG_CONFIG_HOME")
            .map(PathBuf::from)
            .or_else(|| std::env::var_os("HOME").map(|h| PathBuf::from(h).join(".config")))
            .ok_or_else(|| anyhow!("cannot resolve ~/.config"))?;
        Ok(base.join("systemd").join("user"))
    }

    fn service_unit() -> String {
        format!("{TASK_NAME}.service")
    }
    fn timer_unit() -> String {
        format!("{TASK_NAME}.timer")
    }

    fn systemctl(args: &[&str]) -> Result<std::process::Output> {
        Command::new("systemctl")
            .arg("--user")
            .args(args)
            .output()
            .map_err(|e| anyhow!("running systemctl: {e}"))
    }

    pub struct SystemdUser;

    impl ServiceManager for SystemdUser {
        fn install(&self, exe: &Path, interval_minutes: u32) -> Result<()> {
            let dir = unit_dir()?;
            std::fs::create_dir_all(&dir)?;

            let service = format!(
                "[Unit]\nDescription=Webnovel crawler sync\n\n\
                 [Service]\nType=oneshot\nExecStart=\"{}\" sync\n",
                exe.display()
            );
            let timer = format!(
                "[Unit]\nDescription=Webnovel crawler sync timer\n\n\
                 [Timer]\nOnBootSec={interval_minutes}min\nOnUnitActiveSec={interval_minutes}min\n\
                 Persistent=true\n\n\
                 [Install]\nWantedBy=timers.target\n"
            );
            std::fs::write(dir.join(service_unit()), service)?;
            std::fs::write(dir.join(timer_unit()), timer)?;

            let reload = systemctl(&["daemon-reload"])?;
            if !reload.status.success() {
                bail!(
                    "systemctl daemon-reload failed: {}",
                    String::from_utf8_lossy(&reload.stderr).trim()
                );
            }
            let enable = systemctl(&["enable", "--now", &timer_unit()])?;
            if !enable.status.success() {
                bail!(
                    "systemctl enable failed: {}",
                    String::from_utf8_lossy(&enable.stderr).trim()
                );
            }
            Ok(())
        }

        fn uninstall(&self) -> Result<()> {
            let _ = systemctl(&["disable", "--now", &timer_unit()]);
            if let Ok(dir) = unit_dir() {
                let _ = std::fs::remove_file(dir.join(timer_unit()));
                let _ = std::fs::remove_file(dir.join(service_unit()));
            }
            let _ = systemctl(&["daemon-reload"]);
            Ok(())
        }

        fn status(&self) -> Result<ServiceStatus> {
            let out = systemctl(&["is-enabled", &timer_unit()])?;
            let detail = String::from_utf8_lossy(&out.stdout).trim().to_string();
            Ok(ServiceStatus {
                installed: out.status.success(),
                detail: if out.status.success() {
                    format!("timer is {detail}")
                } else {
                    "not installed".to_string()
                },
            })
        }
    }
}

#[cfg(target_os = "macos")]
mod macos {
    use std::path::{Path, PathBuf};
    use std::process::Command;

    use anyhow::{anyhow, bail, Result};

    use super::{ServiceManager, ServiceStatus};

    fn label() -> String {
        "com.webnovelcrawler.sync".to_string()
    }

    fn plist_path() -> Result<PathBuf> {
        let home = std::env::var_os("HOME").ok_or_else(|| anyhow!("cannot resolve $HOME"))?;
        Ok(PathBuf::from(home)
            .join("Library")
            .join("LaunchAgents")
            .join(format!("{}.plist", label())))
    }

    pub struct Launchd;

    impl ServiceManager for Launchd {
        fn install(&self, exe: &Path, interval_minutes: u32) -> Result<()> {
            let path = plist_path()?;
            if let Some(parent) = path.parent() {
                std::fs::create_dir_all(parent)?;
            }
            let plist = format!(
                "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n\
                 <!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \
                 \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n\
                 <plist version=\"1.0\"><dict>\n\
                 <key>Label</key><string>{label}</string>\n\
                 <key>ProgramArguments</key><array><string>{exe}</string><string>sync</string></array>\n\
                 <key>StartInterval</key><integer>{secs}</integer>\n\
                 </dict></plist>\n",
                label = label(),
                exe = exe.display(),
                secs = interval_minutes as u64 * 60
            );
            std::fs::write(&path, plist)?;

            let path_str = path.to_string_lossy().to_string();
            // Reload if already loaded (ignore errors), then load.
            let _ = Command::new("launchctl").args(["unload", &path_str]).output();
            let out = Command::new("launchctl")
                .args(["load", &path_str])
                .output()
                .map_err(|e| anyhow!("running launchctl: {e}"))?;
            if !out.status.success() {
                bail!(
                    "launchctl load failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                );
            }
            Ok(())
        }

        fn uninstall(&self) -> Result<()> {
            if let Ok(path) = plist_path() {
                let _ = Command::new("launchctl")
                    .args(["unload", &path.to_string_lossy()])
                    .output();
                let _ = std::fs::remove_file(&path);
            }
            Ok(())
        }

        fn status(&self) -> Result<ServiceStatus> {
            let out = Command::new("launchctl")
                .arg("list")
                .output()
                .map_err(|e| anyhow!("running launchctl: {e}"))?;
            let listed = String::from_utf8_lossy(&out.stdout)
                .lines()
                .any(|l| l.contains(&label()));
            Ok(ServiceStatus {
                installed: listed,
                detail: if listed {
                    format!("loaded: {}", label())
                } else {
                    "not installed".to_string()
                },
            })
        }
    }
}
