//! Background-service management: registering the periodic `sync` job with the
//! OS scheduler.
//!
//! Windows (Task Scheduler, via `schtasks`) is implemented. Other platforms are
//! stubbed behind the same trait so a systemd user unit / launchd agent can be
//! added later without touching the CLI. Task Scheduler is chosen over a real
//! Windows Service because the sync is a scheduled invocation, not a resident
//! daemon (see DESIGN.md), and a per-user task needs no elevation.

#![allow(dead_code)] // Some fields/impls are platform-gated.

use std::path::Path;

use anyhow::Result;

/// Name of the scheduled task / service.
pub const TASK_NAME: &str = "WebnovelCrawlerSync";

pub struct ServiceStatus {
    pub installed: bool,
    pub detail: String,
}

/// Platform-agnostic install/uninstall/status for the background sync job.
pub trait ServiceManager {
    fn install(&self, exe: &Path, interval_minutes: u32) -> Result<()>;
    fn uninstall(&self) -> Result<()>;
    fn status(&self) -> Result<ServiceStatus>;
}

/// The service manager for the current platform.
pub fn manager() -> Result<Box<dyn ServiceManager>> {
    #[cfg(windows)]
    {
        Ok(Box::new(windows::WindowsTaskScheduler))
    }
    #[cfg(not(windows))]
    {
        anyhow::bail!("background-service install is only implemented on Windows so far")
    }
}

#[cfg(windows)]
mod windows {
    use std::path::{Path, PathBuf};
    use std::process::Command;

    use anyhow::{anyhow, bail, Result};

    use super::{ServiceManager, ServiceStatus, TASK_NAME};

    /// Path to the generated hidden-launcher script (next to the DB).
    fn launcher_path() -> Result<PathBuf> {
        let db = crawler_core::default_db_path()?;
        let dir = db
            .parent()
            .ok_or_else(|| anyhow!("cannot resolve data directory"))?;
        Ok(dir.join("sync-hidden.vbs"))
    }

    /// Write a VBScript that runs `<exe> sync` with a hidden window. Launched via
    /// `wscript.exe` (which has no console of its own), this makes the scheduled
    /// run windowless — no console flash every interval.
    fn write_launcher(path: &Path, exe: &Path) -> Result<()> {
        if let Some(parent) = path.parent() {
            std::fs::create_dir_all(parent)?;
        }
        // Run's first arg is the command line: the quoted exe path + " sync".
        // In VBScript a doubled "" is one literal quote, so `"""..."" sync"`
        // yields the string `"<exe>" sync`. Window style 0 = hidden, async.
        let cmd = format!("\"\"\"{}\"\" sync\"", exe.display());
        let vbs = format!(
            "' Auto-generated by crawler. Runs the sync with no console window.\r\n\
             CreateObject(\"Wscript.Shell\").Run {cmd}, 0, False\r\n"
        );
        std::fs::write(path, vbs)
            .map_err(|e| anyhow!("writing launcher {}: {e}", path.display()))?;
        Ok(())
    }

    pub struct WindowsTaskScheduler;

    impl ServiceManager for WindowsTaskScheduler {
        fn install(&self, exe: &Path, interval_minutes: u32) -> Result<()> {
            // Register `wscript.exe "<launcher.vbs>"` rather than the console exe
            // directly, so the periodic run shows no window.
            let launcher = launcher_path()?;
            write_launcher(&launcher, exe)?;
            let tr = format!("wscript.exe \"{}\"", launcher.display());
            let out = Command::new("schtasks")
                .args([
                    "/Create",
                    "/TN",
                    TASK_NAME,
                    "/TR",
                    &tr,
                    "/SC",
                    "MINUTE",
                    "/MO",
                    &interval_minutes.to_string(),
                    "/F",
                ])
                .output()?;
            if !out.status.success() {
                bail!(
                    "schtasks /Create failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                );
            }
            Ok(())
        }

        fn uninstall(&self) -> Result<()> {
            let out = Command::new("schtasks")
                .args(["/Delete", "/TN", TASK_NAME, "/F"])
                .output()?;
            if !out.status.success() {
                bail!(
                    "schtasks /Delete failed: {}",
                    String::from_utf8_lossy(&out.stderr).trim()
                );
            }
            // Best-effort cleanup of the generated launcher.
            if let Ok(launcher) = launcher_path() {
                let _ = std::fs::remove_file(launcher);
            }
            Ok(())
        }

        fn status(&self) -> Result<ServiceStatus> {
            let out = Command::new("schtasks")
                .args(["/Query", "/TN", TASK_NAME])
                .output()?;
            Ok(ServiceStatus {
                installed: out.status.success(),
                detail: if out.status.success() {
                    String::from_utf8_lossy(&out.stdout).trim().to_string()
                } else {
                    "not installed".to_string()
                },
            })
        }
    }
}
